skip_tags: true

image: Visual Studio 2017

build_script:
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 15 Win64" ..
  - cd ..
  - msbuild.exe build/redream.sln /t:redream /p:Configuration=Release /p:Platform=x64