language: c

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - cmake-data
            - gcc-6
            - g++-6
            - libasound2-dev
            - libpulse-dev
            - libjack-jackd2-dev
      env:
        - BUILD_ARCH=x86_64
        - BUILD_PLATFORM=linux

    - os: osx
      osx_image: xcode8.2
      compiler: clang
      env:
        - BUILD_ARCH=x86_64
        - BUILD_PLATFORM=mac
      before_install:
        - brew update
        - brew outdated cmake || brew upgrade cmake

script:
  - if [ "$CC" = "gcc" ]; then export CC="gcc-6" CXX="g++-6"; fi
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=RELEASE ..
  - make

after_success:
- BUILD_VERSION=`git describe --tags`
- BUILD_ARTIFACT=redream.$BUILD_ARCH-$BUILD_PLATFORM-$BUILD_VERSION.tar.gz
- tar -cvzf $BUILD_ARTIFACT redream
- curl -s -F "token=$DEPLOY_TOKEN" -F "artifact=@$BUILD_ARTIFACT" https://redream.io/deploy/$BUILD_ARTIFACT > /dev/null 2>&1
